package sr.unasat.musiQ_library.utlis;

public class Info {

    public static final String QUEEM_INFO = "Queen are a British rock band formed in London in 1970. Their classic line-up was Freddie Mercury (lead vocals and piano), Brian May (lead guitar and vocals), Roger Taylor (drums and vocals), and John Deacon (bass guitar). Their earliest works were influenced by progressive rock, hard rock and heavy metal, but the band gradually ventured into more conventional and radio-friendly works by incorporating further styles, such as arena rock and pop rock.";

    public static final String BON_JOVI_INFO = "Bon Jovi is an American rock band formed in 1983 in Sayreville, New Jersey. It consists of singer Jon Bon Jovi, keyboardist David Bryan, drummer Tico Torres, guitarist Phil X, and bassist Hugh McDonald. Previous bassist Alec John Such was dismissed in 1994, and longtime guitarist and co-songwriter Richie Sambora left in 2013.";

    public static final String EMINEM_INFO = "Marshall Bruce Mathers III (born October 17, 1972), known professionally as Eminem, is an American rapper, songwriter, record producer, record executive, film producer, and actor. He is consistently cited as one of the greatest and most influential artists of all time in hip hop, with Rolling Stone placing him in its list of the 100 Greatest Artists of All Time and labeling him the \"King of Hip Hop\".";

    public static final String MICHAEL_JACKSON_INFO = "Michael Joseph Jackson (August 29, 1958 – June 25, 2009) was an American singer, songwriter, and dancer. Dubbed the \"King of Pop\", he is widely regarded as one of the most significant cultural figures of the 20th century and one of the greatest entertainers of all time. He was also known for his philanthropy, charitable fundraising, and lifestyle, residing in a private amusement park he called Neverland Ranch and often becoming the focus of tabloid scrutiny. Jackson's contributions to music, dance, and fashion, along with his publicized personal life, made him a global figure in popular culture for over four decades.";

    public static final String NSYNC_INFO = "NSYNC was an American boy band formed in Orlando, Florida, in 1995 and launched in Germany by BMG Ariola Munich. NSYNC consisted of Justin Timberlake, JC Chasez, Chris Kirkpatrick, Joey Fatone, and Lance Bass. After heavily publicized legal battles with their former manager Lou Pearlman and former record label Bertelsmann Music Group, the group's second album, No Strings Attached (2000), sold over one million copies in one day and 2.42 million copies in one week, which was a record for over fifteen years";

    public static final String NWA_INFO = "N.W.A (an abbreviation for Niggaz Wit Attitudes) was an American hip hop group from Los Angeles, California. They were among the earliest and most significant popularizes and controversial figures of the gangsta rap subgenre, and are widely considered one of the greatest and most influential groups in the history of hip hop music.";

    public static final String LINKIN_PARK_INFO = "Linkin Park is an American rock band from Agoura Hills, California. The band's current lineup comprises vocalist/rhythm guitarist Mike Shinoda, lead guitarist Brad Delson, bassist Dave Farrell, turntablist/keyboardist Joe Hahn and drummer Rob Bourdon, all of whom are founding members. Vocalists Mark Wakefield and Chester Bennington and bassist Kyle Christner are former members of the band.";

    public static final String MAROON_5_INFO = "Maroon 5 is an American pop rock band from Los Angeles, California. It currently consists of lead vocalist Adam Levine, keyboardist and rhythm guitarist Jesse Carmichael, bassist Mickey Madden, lead guitarist James Valentine, drummer Matt Flynn, keyboardist PJ Morton, and multi-instrumentalist Sam Farrar. Original members Levine, Carmichael, Madden, and drummer Ryan Dusick first came together as Kara's Flowers in 1994, while they were still in high school.";

    public static final String BRUNO_MARS_INFO = "Peter Gene Hernandez (born October 8, 1985), known professionally as Bruno Mars, is an American singer, songwriter, multi-instrumentalist, record producer, and dancer. He is known for his stage performances, retro showmanship and for performing in a wide range of musical styles including R&B, funk, pop, soul, reggae, hip hop, and rock. Mars is accompanied by his band, The Hooligans, who play a variety of instruments such as electric guitar, bass, piano, keyboards, drums and horns, and also serve as backup singers and dancers.";

    public static final String DAFT_PUNK_INFO = "Daft Punk is a French electronic music duo formed in Paris in 1993 by Guy-Manuel de Homem-Christo and Thomas Bangalter.[5][6][7][8] They achieved popularity in the late 1990s as part of the French house movement, and had success in the years following, combining elements of house music with funk, techno, disco, rock, and synthpop.[2][6][7][9] They have worn ornate helmets and gloves to assume robot personas in most public appearances since 1999[10] and rarely grant interviews or appear on television. The duo were managed from 1996 to 2008 by Pedro Winter (also known as Busy P), the head of Ed Banger Records.";

    public static final String ALICIA_KEYS_INFO = "Alicia Augello Cook (born January 25, 1981), known professionally as Alicia Keys, is an American singer-songwriter, musician, record producer, actress and philanthropist. A classically-trained pianist, Keys was composing songs by age 12 and was signed at 15 years old by Columbia Records.";

    public static final String JAY_Z_INFO = "Shawn Corey Carter (born December 4, 1969), known professionally as Jay-Z (stylized as JAY-Z), is an American rapper, songwriter, record producer, entrepreneur, and record executive. Considered one of the best rappers of all time, he is regarded as one of the world's most significant cultural icons and has been a global figure in popular culture for over two decades.";

    public static final String BEYONCE_INFO = "Beyoncé Giselle Knowles-Carter born September 4, 1981) is an American singer, songwriter, actress, record producer and dancer. Born and raised in Houston, Texas, Beyoncé performed in various singing and dancing competitions as a child. She rose to fame in the late 1990s as lead singer of the R&B girl-group Destiny's Child. Managed by her father, Mathew Knowles, the group became one of the best-selling girl groups in history.";

    public static final String DESTINYS_CHILD_INFO = "Destiny's Child was an American girl group whose final and best-known line-up comprised Beyoncé Knowles, Kelly Rowland, and Michelle Williams. Formed in 1997 in Houston, Texas, Destiny's Child members began their musical career as Girl's Tyme, formed in 1990, comprising Knowles, Rowland, LaTavia Roberson, and LeToya Luckett among others.";

    public static final String BOYZ_II_MEN_INFO = "Boyz II Men is an American R&B vocal group from Philadelphia, Pennsylvania, best known for emotional ballads and a cappella harmonies. They are currently a trio composed of baritone Nathan Morris alongside tenors Wanya Morris and Shawn Stockman. During the 1990s, Boyz II Men found fame on Motown Records as a quartet including bass Michael McCary, who left the group in 2003 due to health issues";

    public static final String TEMPTATIONS_INFO = "The Temptations is an American vocal group who released a series of successful singles and albums with Motown Records during the 1960s and 1970s. The group’s work with producer Norman Whitfield, beginning with the Top 10 hit single \"Cloud Nine\" in October 1968, pioneered psychedelic soul, and was significant in the evolution of R&B and soul music.[1] The band members are known for their choreography, distinct harmonies, and dress style. Having sold tens of millions of albums, the Temptations is among the most successful groups in popular music";

}
